todo/urls.py
import todo
from todo import views
from django.urls import path

app_name = 'todo'

urlpatterns = [

    path('home/', views.homepage, name='home'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('', views.TaskListView.as_view(), name='task_views'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.TaskUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.TaskDeleteView.as_view(), name='delete'),
    path('contact/', views.contact_us, name='contactus')

]

toodo_sytem/urls.py
"""toodo_sytem URL Configuration

"""
from django.contrib import admin
from django.urls import path, include

import todo

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls', namespace='todo')),
]

todo/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


# Create your models here.

class Task(models.Model):
    status_option = [('in progress', 'IN PROGRESS'),
                     ('completed', 'COMPLETED')]

    title = models.CharField(max_length=250)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    due_date = models.DateField()
    task_status = models.CharField(max_length=20, choices=status_option, default='in progress')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('task_views')

todo/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from todo.models import Task


# Create your views here.


def homepage(request):
    return render(request, 'todo/index.html')


# def view_all_tasks(request):
#     all_tasks = models.Task.objects.all()
#     return render(request, 'todo/viewall.html', {'tasks': all_tasks})

class TaskListView(ListView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'todo/viewall.html'


class TaskCreateView(CreateView):
    model = Task
    template_name = 'todo/create.html'
    fields = ['title', 'description', 'user', 'due_date']
    success_url = reverse_lazy('todo:task_views')


class TaskUpdateView(UpdateView):
    model = Task
    template_name = 'todo/update.html'
    context_object_name = 'task'
    fields = ['title', 'description', 'task_status', 'due_date']
    success_url = reverse_lazy('todo:task_views')


class TaskDetailView(DetailView):
    model = Task
    template_name = 'todo/detailview.html'
    context_object_name = 'task'
    fields = ['title', 'description', 'due_date', 'task_status']


class TaskDeleteView(DeleteView):
    model = Task
    field = ['title']
    template_name = 'todo/delete.html'
    context_object_name = 'task'
    success_url = reverse_lazy('todo:task_views')


def contact_us(request):
    return render(request, 'todo/contactus.html')

todo/templates/todo/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body style="background-color: #79aec8; height: 100%">
    <header style="background-color: #1b1b1b; border: 1px solid black;">
          <nav class="navbar bg-body-tertiary fixed-top; background-color: #264b5d" style="position: relative; bottom: 3px">
      <div class="container-fluid">
        <a class="navbar-brand"><h1 style="text-transform: uppercase; font-family: 'Berlin Sans FB',sans-serif">Todo App</h1></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">

          <div class="offcanvas-header">
              <div style="background-color: black; border: 1px solid transparent; width: 65px;height: 45px; border-radius: 6px;">
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel" style="margin: 5px; color: whitesmoke">Menu</h5>
              </div>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body" style="background-color: #747474">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/todo/home/" style="color: white">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: white">
                  Task
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'todo:create' %}">Add New Task</a></li>
                  <li><a class="dropdown-item" href="{% url 'todo:task_views' %}">View Task</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" style="color: white">Contact Us</a>
              </li>
                 <li class="nav-item">
                <a class="nav-link" href="#" style="color: white">Sign out</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    </header>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

todo/templates/todo/base_view.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body style="background-color: #747474; height: 100%;">
    <header style="background-color: #1b1b1b; border: 1px solid black;">
          <nav class="navbar bg-body-tertiary fixed-top; background-color: #264b5d" style="position: relative; bottom: 3px">
      <div class="container-fluid">
        <a class="navbar-brand"><h1 style="text-transform: uppercase; font-family: 'Berlin Sans FB',sans-serif">Todo App</h1></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">

          <div class="offcanvas-header">
              <div style="background-color: black; border: 1px solid transparent; width: 65px;height: 45px; border-radius: 6px;">
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel" style="margin: 5px; color: whitesmoke">Menu</h5>
              </div>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body" style="background-color: #747474">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/todo/home/" style="color: white">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: white">
                  Task
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'todo:create' %}">Add New Task</a></li>
                  <li><a class="dropdown-item" href="{% url 'todo:task_views' %}">View Task</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" style="color: white">Contact Us</a>
              </li>
                 <li class="nav-item">
                <a class="nav-link" href="#" style="color: white">Sign out</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    </header>

 {% block content %}
 {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

todo/templates/todo/contactus.html
{% extends 'todo/base_view.html' %}

{% block title %}
    Contact us
{% endblock %}

{% block content %}
<div>

</div>

{% endblock %}

todo/templates/todo/create.html
{% extends 'todo/base_view.html' %}

{% block title %}
   Create Task
{% endblock %}

{% block content %}
    <div style="margin: 30px; background-color: mediumpurple; height: 100%; width: 50%; padding: 20px">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="SAVE" style="background-color: #272727; color: honeydew;border-radius: 5px; padding: 5px">
        </form>
    </div>
{% endblock %}

todo/templates/todo/delete.html
{% extends 'todo/base_view.html' %}

{% block title %}
   {{ task.title }}
{% endblock %}


{% block content %}
<div style="background-color: #aaaaaa; margin: 30px; padding: 30px; width: 40%">
    <form action="" method="post">
    {% csrf_token %}
   {{ form.as_p }}
        <p style="font-weight: bolder; text-transform: uppercase; margin: 0 0 40px 60px"> {{ task.title }}</p>
    <input type="submit" value="DELETE">
        <a href="{% url 'todo:detail' task.pk %}" style="margin-left: 50px; background-color: #264b5d; padding: 5px; font-size: small; color: white; text-decoration: none; border-radius: 5px">CANCEL</a>
</form>
</div>
{% endblock %}

todo/templates/todo/detailview.html
{% extends 'todo/base_view.html' %}

{% block title %}
   {{ task.title }}
{% endblock %}

{% block content %}
<div style="background-color: slateblue; border: 2px solid black;border-radius: 10px; margin: 100px; padding:50px;width: 500px; height: 350px;text-align: center">
<h3 style="margin-bottom: 20px; text-decoration: underline">{{ task.title.upper }}</h3>
<h5 style="margin: 20px">Description-> {{ task.description }}</h5>
    <p>Due-Date --> {{ task.due_date }}</p>
<p style="margin-bottom:50px">Task Status --> <span style="margin-left: 10px; background-color: #121212; color: #bbccdd; padding: 10px; border-radius: 3px;">{{ task.task_status }}</span></p>
    <a href="{% url 'todo:update' task.pk %}" style="margin-right: 25px; text-decoration:none; background-color: #006b1b; width: 30%; padding: 5px; color: white;border-radius: 5px; display: inline-block">UPDATE </a>
    <a href="{% url 'todo:delete' task.pk %}" style="display: inline-block; margin-left:70px;background-color: #570808; text-decoration:none;padding: 5px; width: 30%; color: white; border-radius: 5px;">DELETE</a>

</div>

{% endblock %}

todo/templates/todo/index.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Home</title>#}
{#</head>#}
{#<body style="margin: 0">#}
{#    <header style="background-color: #5b80b2;#}
{#    text-align: center; display:block;#}
{#    width: content-box;#}
{#    margin: 0 0 20px;#}
{#    position: relative;#}
{#    bottom: 23px;#}
{#    height: 80px; text-transform: uppercase">#}
{#         <h1 style="background-color: #00363a; color: ghostwhite;#}
{#         position: relative;#}
{#         top: 38px;#}
{#         border-radius: 6px;#}
{#         font-family: 'Berlin Sans FB',sans-serif;#}
{#         border: 1px solid transparent; width: 200px">Todo App</h1>#}
{#        <nav><a href="{% url 'test' %}" >Log Out</a></nav>#}
{#    </header>#}
{#</body>#}
{#</html>#}

{% extends 'todo/base.html' %}

{% block title %}
    Home
{% endblock %}

 {% block content %}
     <div style="background-color: #1b1b1b; padding: 50px; width: 800px; position:relative; left: 220px; top: 80px; border-radius: 10px; box-shadow: black">
     <p style="color: white; font-size: 25px">Introducing the ultimate task app.
         The solution for managing your busy life!
         Our task app is designed to help you stay organized,
         prioritize your to-do list, and achieve your goals,
         all in one easy-to-use platform.</p>
     </div>
{#     <div style="position:absolute; background-color: #bbccdd; bottom: 40px; margin: 10px; padding: 5px; height: 50px; border-radius: 5px">#}
{#         <p style="color: black; font-weight: bold; padding: 5px;"><a href="" style="text-decoration: none; color: #212121">Contact us</a></p>#}
{#     </div>#}


 {% endblock %}

todo/templates/todo/logout.html
{% extends 'todo/base.html' %}

{% block title %}
    Sign Out
{% endblock %}

{% block content %}

{% endblock %}

todo/templates/todo/update.html
{% extends 'todo/base_view.html' %}

{% block title %}
   Update
{% endblock %}

{% block content %}
<div style="background-color: #6f94c6; border: 2px solid black; margin: 20px; padding: 20px; width: 50%">

<form action="" method="post">
    {% csrf_token %}
   {{ form.as_p }}
    <input type="submit" value="UPDATE" style="background-color: #1b1b1b; color: white; padding: 5px">
</form>

</div>

{% endblock %}

todo/templates/todo/viewall.html
{% extends 'todo/base_view.html' %}

{% block title %}
   Tasks
{% endblock %}

{% block content %}
    <main style="margin: 10px">
   <div>
       {% for task in tasks %}
       <ul >
           <li style="margin: 30px">
              <h3><a href="{% url 'todo:detail' task.pk  %}" style="text-decoration: none; color: white">{{ task.title.title }}</a></h3>
             <span style="background-color: black;
              color: white; display: inline-block;
               border: 1px solid transparent; padding: 10px; border-radius: 5px">Due-Date =>
                &nbsp {{ task.due_date }}</span>
               <small style="display: inline-block;
                position: relative; left: 200px;
                bottom: 25px; background-color: #447e9b;
                padding: 10px; border-radius: 5px">{{ task.task_status }}</small>
           </li>
       </ul>
       {% endfor %}
    </div>
    </main>

{% endblock %}